#ifndef __DINGOO_h_
#define __DINGOO_h_

#define BUTTON_UP SDLK_UP
#define BUTTON_DOWN SDLK_DOWN
#define BUTTON_RIGHT SDLK_RIGHT
#define BUTTON_LEFT SDLK_LEFT
#define BUTTON_R SDLK_BACKSPACE
#define BUTTON_L SDLK_TAB
#define BUTTON_A SDLK_LCTRL
#define BUTTON_B SDLK_LALT
#define BUTTON_X SDLK_SPACE
#define BUTTON_Y SDLK_LSHIFT
#define BUTTON_SELECT SDLK_ESCAPE
#define BUTTON_START SDLK_RETURN

#endif // __DINGOO_h_
